services:
  - type: web
    name: fishgoghogh
    runtime: node
    buildCommand: npm install
    startCommand: npm start
    rootDir: .
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000